name: Flask App CI/CD with Docker

on:
  push:
    branches: [main]

jobs:
  flask-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t flask-to-do-app .

      - name: Run Flask app inside Docker container
        run: |
          docker run -d -p 5000:5000 --name flask_container flask-to-do-app
          sleep 10

      - name: Verify Flask app is running
        run: |
          docker ps
          curl http://localhost:5000
