name: Flask App CI/CD (No Docker)

on:
  push:
    branches: [main]

jobs:
  run-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Flask app in background
        run: |
          nohup python app.py > flask.log 2>&1 &
          sleep 10

      - name: Print Flask logs
        run: cat flask.log

      - name: Ping Flask app
        run: curl http://127.0.0.1:5000
