name: CI
on:
  pull_request:

jobs:
  deploy-to-minikube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Start minikube
      uses: medyagh/setup-minikube@latest

    - name: Try the cluster
      run: kubectl get pods -A

    - name: Build Docker image
      run: minikube image build -t local/example:latest .

    - name: Deploy to minikube
      run: |
        kubectl apply -f deploy/k8s.yaml
        kubectl wait --for=condition=ready pod -l app=example

    - name: Test Service
      run: |
        minikube service list
        minikube service example --url
        curl $(minikube service example --url)
